query BlogPreview {
	publication(host: "jamesreed.dev") {
		title
		posts(first: 4) {
			edges {
				node {
					title
					brief
					slug
					url
					coverImage {
						url
					}
				}
			}
		}
	}
}
